version: '3'

services:
  dubboadmin:
    image: apache/dubbo-admin
    container_name: dubboadmin
    ports:
      - 8082:8080
    environment:
      - admin.registry.address=zookeeper://192.168.107.99:2181,zookeeper://192.168.107.99:2182,zookeeper://192.168.107.99:2183
      - admin.config-center=zookeeper://192.168.107.99:2188
      - admin.metadata-report.address=zookeeper://192.168.107.99:2188     
    restart: always
  dubboadmin2:
    image: chenchuxin/dubbo-admin
    container_name: dubboadmin2
    ports:
      - 8081:8080
    environment:
      - dubbo.registry.address=zookeeper://192.168.107.99:2188
      - dubbo.admin.root.password=root
      - dubbo.admin.guest.password=guest
    restart: always
