version: '3'
services:
  java8:
    image: 'java:8-jdk-alpine'
    restart: always
    volumes:
      - ./data:/tmp/javaapp
    ports:
      - 6006:8080
    command: java -jar /tmp/javaapp/XLServer-0.0.1-SNAPSHOT.jar"
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
