version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'git.xiaolingenglish.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.xiaolingenglish.com:51101'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'xiaolingadmin@163.com'
        gitlab_rails['gitlab_email_display_name'] = 'Gitlab Admin'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@xiaolingenglish.com'
        gitlab_rails['gitlab_email_subject_suffix'] = 'gitlab-'
        
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.163.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "xiaolingadmin@163.com"
        gitlab_rails['smtp_password'] = "xlshouquanma2019"
        gitlab_rails['smtp_domain'] = "163.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        
        #gitlab_rails['gitlab_ssh_host'] = 'git.xiaolingenglish.com'
        # ssh¶Ë¿ÚºÅ
        gitlab_rails['gitlab_shell_ssh_port'] = 51102
        
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
          main:
            label: 'LDAP'
            host: 'ldap.xiaolingenglish.com'
            port: 389
            uid: 'uid'
            bind_dn: 'cn=admin,dc=xiaolingenglish,dc=com'
            password: '=0oxlMike17'
            encryption: 'plain'
            active_directory: true
            allow_username_or_email_login: true
            block_auto_created_users: false
            base: 'ou=users,ou=xl,dc=xiaolingenglish,dc=com'
            group_base: 'ou=groups,ou=xl,dc=xiaolingenglish,dc=com'
            user_filter: ''
            attributes:
              username: ['uid', 'userid', 'sAMAccountName','cn']
              email:    ['mail', 'email', 'userPrincipalName']
              name:       'cn'
              first_name: 'givenName'
              last_name:  'sn'
        EOS
    ports:
      - '51101:51101'
      - '51102:51102'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    networks:
      - "dev"
networks:
  dev:
    driver: bridge