version: '3'
services:
  Ewomail:
    image: 'microsoft/iis:latest'
    restart: always
    hostname: 'mail.xiaolingenglish.com'
    ports:  
      - "53000:80"
    volumes:
      # - ./postfix:/etc/postfix

    networks:
      - "dev"
networks:
  dev:
    driver: bridge




