version: '3'
services:
  gogs:
    image: gogs/gogs
    restart: always
    ports:
      - "10022:22"
      - "10080:3000"
    environment:
      - TZ=Asia/Shanghai      
    volumes:
      - ./data:/data
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
